spring:
  application:
    name: learnvault-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/learnvault
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
